
include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-$(CONFIG_MTK_LENS_OV8825AF_SUPPORT) += ov8825af/
obj-$(CONFIG_MTK_LENS_OV8826AF_SUPPORT) += ov8826af/
obj-$(CONFIG_MTK_LENS_OV8827AF_SUPPORT) += ov8827af/
