/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT6589_NP. Copyright MediaTek Inc. (C) 2013.
 * Tue Jan  6 01:09:06 2015
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H


#define AUXADC_TEMPERATURE_CHANNEL     3


#endif //_CUST_AUXADC_TOOL_H


