/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6  for MT6589_NP. Copyright MediaTek Inc. (C) 2013.
 * Tue Jan  6 01:09:06 2015
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


